"""remove resume id from profession table

Revision ID: 0786398e6b71
Revises: d544a05c3ce1
Create Date: 2024-08-25 12:39:43.748532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0786398e6b71'
down_revision: Union[str, None] = 'd544a05c3ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('professionalinfo_resume_id_fkey', 'professionalinfo', type_='foreignkey')
    op.drop_column('professionalinfo', 'resume_id')
    op.add_column('resume', sa.Column('professional_info_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resume', 'professionalinfo', ['professional_info_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_column('resume', 'professional_info_id')
    op.add_column('professionalinfo', sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('professionalinfo_resume_id_fkey', 'professionalinfo', 'resume', ['resume_id'], ['id'])
    # ### end Alembic commands ###
