"""added ids in resume table

Revision ID: 1cfd5659a8bb
Revises: 73aeaf4025f3
Create Date: 2024-08-25 02:43:50.668844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfd5659a8bb'
down_revision: Union[str, None] = '73aeaf4025f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('steps_id', sa.Integer(), nullable=True))
    op.add_column('resume', sa.Column('professional_info_id', sa.Integer(), nullable=True))
    op.add_column('resume', sa.Column('social_media_id', sa.Integer(), nullable=True))
    op.add_column('resume', sa.Column('experience_id', sa.Integer(), nullable=True))
    op.add_column('resume', sa.Column('education_id', sa.Integer(), nullable=True))
    op.add_column('resume', sa.Column('projects_id', sa.Integer(), nullable=True))
    op.add_column('resume', sa.Column('certifications_id', sa.Integer(), nullable=True))
    op.add_column('resume', sa.Column('languages_id', sa.Integer(), nullable=True))
    op.add_column('resume', sa.Column('references_id', sa.Integer(), nullable=True))
    op.add_column('resume', sa.Column('extra_info_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resume', 'experience', ['experience_id'], ['id'])
    op.create_foreign_key(None, 'resume', 'professionalinfo', ['professional_info_id'], ['id'])
    op.create_foreign_key(None, 'resume', 'resumesteps', ['steps_id'], ['id'])
    op.create_foreign_key(None, 'resume', 'references', ['references_id'], ['id'])
    op.create_foreign_key(None, 'resume', 'socialmedia', ['social_media_id'], ['id'])
    op.create_foreign_key(None, 'resume', 'certifications', ['certifications_id'], ['id'])
    op.create_foreign_key(None, 'resume', 'education', ['education_id'], ['id'])
    op.create_foreign_key(None, 'resume', 'languages', ['languages_id'], ['id'])
    op.create_foreign_key(None, 'resume', 'projects', ['projects_id'], ['id'])
    op.create_foreign_key(None, 'resume', 'extrainfo', ['extra_info_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_column('resume', 'extra_info_id')
    op.drop_column('resume', 'references_id')
    op.drop_column('resume', 'languages_id')
    op.drop_column('resume', 'certifications_id')
    op.drop_column('resume', 'projects_id')
    op.drop_column('resume', 'education_id')
    op.drop_column('resume', 'experience_id')
    op.drop_column('resume', 'social_media_id')
    op.drop_column('resume', 'professional_info_id')
    op.drop_column('resume', 'steps_id')
    # ### end Alembic commands ###
