"""added resume id in professionalInfo

Revision ID: 3f34b2c61cd0
Revises: 0786398e6b71
Create Date: 2024-08-25 21:38:18.825581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f34b2c61cd0'
down_revision: Union[str, None] = '0786398e6b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionalinfo', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'professionalinfo', 'resume', ['resume_id'], ['id'])
    op.drop_constraint('resume_professional_info_id_fkey', 'resume', type_='foreignkey')
    op.drop_column('resume', 'professional_info_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('professional_info_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('resume_professional_info_id_fkey', 'resume', 'professionalinfo', ['professional_info_id'], ['id'])
    op.drop_constraint(None, 'professionalinfo', type_='foreignkey')
    op.drop_column('professionalinfo', 'resume_id')
    # ### end Alembic commands ###
