"""create table for resume

Revision ID: 4620939a3532
Revises: e08ea7d2578a
Create Date: 2024-08-16 00:01:10.425397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4620939a3532'
down_revision: Union[str, None] = 'e08ea7d2578a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinfo')
    op.add_column('user', sa.Column('role', sa.String(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('resumes', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'resume', ['resumes'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'resumes')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'role')
    op.create_table('userinfo',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('professional_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='userinfo_pkey')
    )
    # ### end Alembic commands ###
