"""add session and remove token

Revision ID: 5e0f125544df
Revises: fb447933089e
Create Date: 2024-08-31 23:58:08.990129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0f125544df'
down_revision: Union[str, None] = 'fb447933089e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
