"""change education table to make resume

Revision ID: 74d8f4d6affe
Revises: 782d9791626b
Create Date: 2024-08-21 00:25:59.012806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d8f4d6affe'
down_revision: Union[str, None] = '782d9791626b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
