"""change resume table 

Revision ID: 847858ef886b
Revises: fdb932f96608
Create Date: 2024-08-16 11:43:29.977336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '847858ef886b'
down_revision: Union[str, None] = 'fdb932f96608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('resumes', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'resume', ['resumes'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'resumes')
    # ### end Alembic commands ###
