"""added steps table and image  column

Revision ID: aa53babfff3f
Revises: 1f18711df94c
Create Date: 2024-08-17 20:40:45.646032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'aa53babfff3f'
down_revision: Union[str, None] = '1f18711df94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionalinfo', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professionalinfo', 'image')
    # ### end Alembic commands ###
