"""create job application table

Revision ID: b2b2f69bd23a
Revises: c7cec41ac1e5
Create Date: 2024-08-25 00:59:56.711150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b2b2f69bd23a'
down_revision: Union[str, None] = 'c7cec41ac1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coverletter', sa.Column('cover_letter_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobapplication', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'jobapplication', 'user', ['user_id'], ['id'])
    op.add_column('resume', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('resume', sa.Column('resume_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('resume', sa.Column('template_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('resume', sa.Column('ats_score', sa.Float(), nullable=True))
    op.add_column('resume', sa.Column('access', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'access')
    op.drop_column('resume', 'ats_score')
    op.drop_column('resume', 'template_color')
    op.drop_column('resume', 'resume_template')
    op.drop_column('resume', 'title')
    op.drop_constraint(None, 'jobapplication', type_='foreignkey')
    op.drop_column('jobapplication', 'user_id')
    op.drop_column('coverletter', 'cover_letter_template')
    # ### end Alembic commands ###
