"""change language as list

Revision ID: bf810823f1dd
Revises: f44ab1a8b628
Create Date: 2024-08-21 02:20:17.821435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf810823f1dd'
down_revision: Union[str, None] = 'f44ab1a8b628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'languages',  # Name of the table
        'language',   # Name of the column to alter
        type_=sa.JSON(),  # New type of the column
        existing_type=sa.JSON(),  # Existing type of the column
        existing_nullable=True,  # Adjust this if the column can be nullable
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'languages',  # Name of the table
        'language',   # Name of the column to alter
        type_=sa.JSON(),  # Reverting to the previous type (assuming it was JSON)
        existing_type=sa.JSON(),  # Existing type of the column
        existing_nullable=True,  # Adjust this if the column can be nullable
    )
    # ### end Alembic commands ###
