"""change language and social media table

Revision ID: c209817b9984
Revises: 74d8f4d6affe
Create Date: 2024-08-21 01:34:12.301874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c209817b9984'
down_revision: Union[str, None] = '74d8f4d6affe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
     op.drop_column('languages', 'proficiency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('proficiency', postgresql.ENUM('beginner', 'intermediate', 'advanced', 'native', name='languageproficiency'), autoincrement=False, nullable=True))
    op.alter_column(
        'languages', 
        'language',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        nullable=True,
        postgresql_using='language::text'
    )
    # ### end Alembic commands ###
