"""added cover letter table 

Revision ID: c7cec41ac1e5
Revises: a4143612965b
Create Date: 2024-08-21 23:33:31.124527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7cec41ac1e5'
down_revision: Union[str, None] = 'a4143612965b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resume', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_resumes_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'resumes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('resumes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_resumes_fkey', 'user', 'resume', ['resumes'], ['id'])
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_column('resume', 'user_id')
    # ### end Alembic commands ###
