"""remove ids in resume table

Revision ID: d544a05c3ce1
Revises: 1cfd5659a8bb
Create Date: 2024-08-25 02:53:14.141261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd544a05c3ce1'
down_revision: Union[str, None] = '1cfd5659a8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resume_social_media_id_fkey', 'resume', type_='foreignkey')
    op.drop_constraint('resume_steps_id_fkey', 'resume', type_='foreignkey')
    op.drop_constraint('resume_extra_info_id_fkey', 'resume', type_='foreignkey')
    op.drop_constraint('resume_languages_id_fkey', 'resume', type_='foreignkey')
    op.drop_constraint('resume_references_id_fkey', 'resume', type_='foreignkey')
    op.drop_constraint('resume_education_id_fkey', 'resume', type_='foreignkey')
    op.drop_constraint('resume_experience_id_fkey', 'resume', type_='foreignkey')
    op.drop_constraint('resume_professional_info_id_fkey', 'resume', type_='foreignkey')
    op.drop_constraint('resume_certifications_id_fkey', 'resume', type_='foreignkey')
    op.drop_constraint('resume_projects_id_fkey', 'resume', type_='foreignkey')
    op.drop_column('resume', 'projects_id')
    op.drop_column('resume', 'professional_info_id')
    op.drop_column('resume', 'extra_info_id')
    op.drop_column('resume', 'certifications_id')
    op.drop_column('resume', 'languages_id')
    op.drop_column('resume', 'experience_id')
    op.drop_column('resume', 'references_id')
    op.drop_column('resume', 'education_id')
    op.drop_column('resume', 'social_media_id')
    op.drop_column('resume', 'steps_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('steps_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resume', sa.Column('social_media_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resume', sa.Column('education_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resume', sa.Column('references_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resume', sa.Column('experience_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resume', sa.Column('languages_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resume', sa.Column('certifications_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resume', sa.Column('extra_info_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resume', sa.Column('professional_info_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resume', sa.Column('projects_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('resume_projects_id_fkey', 'resume', 'projects', ['projects_id'], ['id'])
    op.create_foreign_key('resume_certifications_id_fkey', 'resume', 'certifications', ['certifications_id'], ['id'])
    op.create_foreign_key('resume_professional_info_id_fkey', 'resume', 'professionalinfo', ['professional_info_id'], ['id'])
    op.create_foreign_key('resume_experience_id_fkey', 'resume', 'experience', ['experience_id'], ['id'])
    op.create_foreign_key('resume_education_id_fkey', 'resume', 'education', ['education_id'], ['id'])
    op.create_foreign_key('resume_references_id_fkey', 'resume', 'references', ['references_id'], ['id'])
    op.create_foreign_key('resume_languages_id_fkey', 'resume', 'languages', ['languages_id'], ['id'])
    op.create_foreign_key('resume_extra_info_id_fkey', 'resume', 'extrainfo', ['extra_info_id'], ['id'])
    op.create_foreign_key('resume_steps_id_fkey', 'resume', 'resumesteps', ['steps_id'], ['id'])
    op.create_foreign_key('resume_social_media_id_fkey', 'resume', 'socialmedia', ['social_media_id'], ['id'])
    # ### end Alembic commands ###
