"""add type in resume

Revision ID: dec1f070a883
Revises: b2b2f69bd23a
Create Date: 2024-08-25 01:20:15.783045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec1f070a883'
down_revision: Union[str, None] = 'b2b2f69bd23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('type', sa.Enum('generic', 'job', name='resumetype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'type')
    # ### end Alembic commands ###
