"""add col in language

Revision ID: f44ab1a8b628
Revises: c209817b9984
Create Date: 2024-08-21 01:41:33.783599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f44ab1a8b628'
down_revision: Union[str, None] = 'c209817b9984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE languages 
        SET language = json_build_object('language', language)
    """)

    # Alter the column to JSON type
    op.alter_column(
        'languages',
        'language',
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        postgresql_using='language::json'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('languages', 'language',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               nullable=True,
               postgresql_using='language::text')
    # ### end Alembic commands ###
