"""added token, session,oauth in user table

Revision ID: fb447933089e
Revises: fc784a2313ce
Create Date: 2024-08-31 00:52:15.393840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'fb447933089e'
down_revision: Union[str, None] = 'fc784a2313ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('oauth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('oauth_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'session_token')
    op.drop_column('user', 'oauth_id')
    op.drop_column('user', 'oauth_provider')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
