"""add title in job

Revision ID: fc784a2313ce
Revises: 3f34b2c61cd0
Create Date: 2024-08-29 22:54:09.356309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc784a2313ce'
down_revision: Union[str, None] = '3f34b2c61cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobapplication', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobapplication', 'title')
    # ### end Alembic commands ###
